# Generated by Django 3.0.2 on 2020-01-20 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Laptop_block',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_name', models.CharField(max_length=40, verbose_name='Название блока')),
                ('block_description', models.CharField(max_length=250, verbose_name='Описание блока')),
                ('laptop_image', models.CharField(max_length=1200, verbose_name='Ссылка на обложку')),
            ],
            options={
                'verbose_name': 'Блок с ноутбуком',
                'verbose_name_plural': 'Блоки с ноутбуками',
            },
        ),
        migrations.CreateModel(
            name='Main_skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=40, verbose_name='Название навыка')),
                ('skill_description', models.CharField(max_length=250, verbose_name='Описание навыка')),
                ('skill_icon_class', models.CharField(max_length=40, verbose_name='CSS класс иконки навыка')),
            ],
            options={
                'verbose_name': 'Главный навык',
                'verbose_name_plural': 'Главные навыки',
            },
        ),
    ]
