# Generated by Django 3.0.2 on 2020-01-20 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptop_block',
            name='block_name',
            field=models.CharField(max_length=60, verbose_name='Название блока'),
        ),
        migrations.AlterField(
            model_name='main_skill',
            name='skill_icon_class',
            field=models.CharField(max_length=60, verbose_name='CSS класс иконки навыка'),
        ),
        migrations.AlterField(
            model_name='main_skill',
            name='skill_name',
            field=models.CharField(max_length=60, verbose_name='Название навыка'),
        ),
    ]
