# Generated by Django 3.0.2 on 2020-01-22 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Other_request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(max_length=60, verbose_name='Имя отправителя')),
                ('sender_email', models.EmailField(max_length=180, verbose_name='Email отправителя')),
                ('sender_text', models.TextField(verbose_name='Сообщение отправителя')),
            ],
            options={
                'verbose_name': 'Запрос на другое',
                'verbose_name_plural': 'Запросы на другое',
            },
        ),
        migrations.CreateModel(
            name='Project_ask_request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(max_length=60, verbose_name='Имя отправителя')),
                ('sender_email', models.EmailField(max_length=150, verbose_name='Email отправителя')),
                ('sender_text', models.TextField(verbose_name='Сообщение отправителя')),
            ],
            options={
                'verbose_name': 'Запрос на вопрос по проекту',
                'verbose_name_plural': 'Запросы на вопрос по проекту',
            },
        ),
        migrations.CreateModel(
            name='Project_request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(max_length=60, verbose_name='Имя отправителя')),
                ('sender_email', models.EmailField(max_length=150, verbose_name='Email отправителя')),
                ('sender_text', models.TextField(verbose_name='Сообщение отправителя')),
            ],
            options={
                'verbose_name': 'Запрос на проект',
                'verbose_name_plural': 'Запросы на проект',
            },
        ),
        migrations.CreateModel(
            name='Website_error_request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(max_length=60, verbose_name='Имя отправителя')),
                ('sender_email', models.EmailField(max_length=180, verbose_name='Email отправителя')),
                ('sender_text', models.TextField(verbose_name='Сообщение отправителя')),
            ],
            options={
                'verbose_name': 'Запрос на ошибку в сайте',
                'verbose_name_plural': 'Запросы на ошибку в сайте',
            },
        ),
    ]
