# Generated by Django 3.0.2 on 2020-01-21 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=60, verbose_name='Название')),
                ('project_description', models.TextField(verbose_name='Описание')),
                ('project_short_description', models.CharField(max_length=250, verbose_name='Краткое описание')),
                ('project_cover', models.CharField(max_length=1200, verbose_name='Ссылка на обложку')),
                ('start_date', models.CharField(max_length=10, verbose_name='Дата начала работы')),
                ('end_date', models.CharField(max_length=10, verbose_name='Дата окончания работы')),
                ('used_tech', models.TextField(verbose_name='Использованные технологии (через , + пробел)')),
                ('used_tech_link', models.TextField(verbose_name='Ссылки на технологии (через , + пробел)')),
                ('repo_link', models.CharField(max_length=1200, verbose_name='Ссылка на исходный код')),
                ('view_link', models.CharField(max_length=1200, verbose_name='Ссылка на готовый проект')),
                ('project_status', models.IntegerField(verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
            },
        ),
    ]
