# Generated by Django 3.0.2 on 2020-01-20 18:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('about_me', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='edu_period',
            field=models.CharField(default=django.utils.timezone.now, max_length=17, verbose_name='Период обучения'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='work',
            name='work_period',
            field=models.CharField(default=django.utils.timezone.now, max_length=17, verbose_name='Период работы'),
            preserve_default=False,
        ),
    ]
